# Generated by Django 5.0.14 on 2025-11-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_size', models.PositiveSmallIntegerField(choices=[(5, '5 x 5'), (7, '7 x 7'), (9, '9 x 9')], default=5)),
            ],
        ),
    ]
