# Generated by Django 5.0.14 on 2025-11-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='board_size',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
